//Sisipho Tukushe
//Guessing random number.
//22 June 2022
import java.util.Scanner;
import java.util.function.DoubleToIntFunction;

/**
 * Guessing random number class. The user has 5 chances to guess the random number generated by the system.
 */
public class Guessing {
    double randomNumber=0;
    boolean found=false;
    int count=0;

    /**
     * Constructor of Guessing class
     */
    public Guessing()
    {
        randomNumber = Math.ceil (Math.random()*10) ;
    }

    /**
     * Method that gives the result of the guess number
     * @param guess the number that is guessed by the user to be the random number
     * @return a string stating whether the guess is higher/lower or the correct random number
     */
    private String guessResult(int guess)
    {
        count++ ;
        if (guess<randomNumber)
        {
            return "Your guess is low.";
        }
        else if (guess>randomNumber)
            return "Your guess is high.";
        found = true;
        return "You guessed correct! The random number is "+randomNumber+".";
    }

    /**
     * The main method that interacts class with user
     * @param args
     */
    public static void main(String[] args)
     {
         Scanner keyboard = new Scanner(System.in);
         Guessing g = new Guessing();
         System.out.println(g.randomNumber);
         System.out.println("Guess the random number. You have 5 chances to guess.");

         while (g.found==false){
             if (g.count>=5)
             {
                 System.out.println("5 strikes done. Game over! The random number was "+g.randomNumber+".");
                 break;
             }
             else
             {
                 int userGuess = keyboard.nextInt();
                 System.out.println(g.guessResult(userGuess));
             }

         }
     }
}




